#!/bin/bash

set INPFILE=$argv[1]

touch /var/www/html/gamess/$INPFILE.script

echo '#~/bin/bash' > /var/www/html/gamess/$INPFILE.script

#PBS -V

#PBS -q batch

#PBS -l nodes=1:ppn=16

#PBS -l walltime=70:00:00

cd /var/www/html/uploads

pwd

/software/gamess/rungms $1 00 1
